### ISSUE TITLE
Installation process stuck

### ISSUE THREAD

**Issue by Mahmood-Hussain** [openclassify/openclassify#1176]
**Describe the bug**
I simply tried to install the application by following the instructions provided by author 1. Clone, 2. Install dependencies, 3. Change .env file credentials
I see in PHPMyAdmin there are 23 tables but the process is stuck here
![image](https://user-images.githubusercontent.com/31275645/135378759-d9d687bc-00a2-47b0-b31a-656253bd7171.png)

**To Reproduce**
1. Clone 
2. 2. Install dependencies `composer install`
3. Change .env file credentials database details
4.  php artisan install --ready

**Expected behavior**
Run normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Browser chrome
 - Version <not required>

**Smartphone (please complete the following information):**

**Additional context**

PHP version: tried both on 7.4 and 8.0 

@fatihalp Please help!

thank you

**Comment by fatihalp** [comment]
hello @Mahmood-Hussain 
it seems there is no problem with our linux servers right now. Can you just delete connect module and try again?
Let us try installation on mac in that time

**Comment by Mahmood-Hussain** [comment]
@fatihalp  thanks a lot for your reply! I really appreciate it.

I found that there is an issue with my Mac it has some NVRAM cache issues. It even does not work for ssh and your code works smoothly on linux

Thank You
