### ISSUE TITLE
Managed to install but none of the links work 

### ISSUE THREAD

**Issue by moedawood** [openclassify/openclassify#1195]
Hi 

I managed to install the php project but none of my links work at all 

Did I miss Something ?

eg: http://localhost/advs/list gives me a 404 not found

**Comment by RealMurphy** [comment]
Just in case someone may hit this problem and is stranded: For the apache web server, it needs to have .htaccess overrides enabled for the `public` directory and mod_rewrite must be enabled.

**Comment by moedawood** [comment]
Good day,

Thank-you for your email, in order to streamline support requests and serve you better, we utilise a support ticket system, a ticket has been created for you and a member of our support team will be assigned to your request and will follow-up with you as soon as possible. 

Please note that our business hours are:
Mon - Fri : 08:00 - 16:00
Sat + Sun : Closed
Public Holidays: ClosedKind Regards
Your Friendly PiShop Team

[https://ci3.googleusercontent.com/proxy/_qrIf5zI7cjL1Cbvd8hYhGwdGiz4CZNzBJLUZQyS8Uyp3V03mUhILWJKOCQzh8U7xFCmNwgnmo2DXGfVhYkYexRs=s0-d-e1-ft#https://www.pishop.co.za/email-sig-logo-300.jpg]



REF: d0d7fdca969e73795f0bee0a2e967ae4:3733
