### ISSUE TITLE
Composer requires PHP 8

### ISSUE THREAD

**Issue by loranger** [openclassify/openclassify#1284]
Hi,

I just met the same issue encountered in the #1111 :
I use the docker image `nanoninja/php-fpm:latest` which seems to be php 7.4.10 but composer requires a PHP 8

What did I miss ?

**To Reproduce**
1. Create new project
2. Populate .env
3. run docker-compose up

```bash
docker-compose run --rm php php artisan install --ready

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.10. in /var/www/html/vendor/composer/platform_check.php on line 24
```

**Expected behavior**
If openclassify is not PHP8 compliant yet, it should not include PHP8 dependencies, o maybe nanoninja should provide php-fpm 8 images

**Desktop (please complete the following information):**
 - OS: macOS 12.2
 - Browser Firefox
 - Version 98.0a1

**Comment by ChDUP** [comment]
Hi
exactly same issue for me.

**Comment by loranger** [comment]
Beacuse of the lack of support, I tried to figure out alone how I can run openclassify using docker. 
I started again from scratch.

I did clone the whole repository

```shell
git clone git@github.com:openclassify/openclassify.git
cd openclassify
```

I did populate a `.env` file from the demo one provided

```shell
cp .env_demo .env
```

I changed `DB_USERNAME` and `DB_PASSWORD` env variables from the new `.env` file

I also added those missing env variables after the DB_* part inside `.env` file in order to avoid the `WARNING: The XXX variable is not set. Defaulting to a blank string.` [errors](1208)

```
MYSQL_HOST=${DB_HOST}
MYSQL_VERSION=8.0
MYSQL_DATABASE=${DB_DATABASE}
MYSQL_ROOT_PASSWORD=averysecretpassword
MYSQL_USER=${DB_USERNAME}
MYSQL_PASSWORD=${DB_PASSWORD}
NGINX_HOST=openclassify.local
PHP_VERSION=7.4.10
```

I did add the following directive for the `php` and `mysqldb` services inside `docker-compose.yml`, as I'm running on M1

```yaml
    service:
        image: ...
        platform: linux/x86_64
```

I added the volume directive for `composer` service inside `docker-composer.yml` otherwise composer won't install anything

```yaml
    composer:
        image: "composer"
        volumes:
            - "./:/app"
```

Then I was able to run the container. Composer did install all dependencies without complaining about [PHP 8](https://github.com/openclassify/openclassify/issues?q=is%3Aissue+php8+) this time.

Then I fired my browser and reached the webpage:
 
<img width="1023" alt="Capture d’écran 2022-03-14 à 15 57 12" src="https://user-images.githubusercontent.com/6014/158198970-eb1558aa-fa7a-4c33-a0dd-55d216152b0e.png">

I've read in the issues openclassify does not officially support PHP 8. 
All right, but could someone provide a way to run openclassify with PHP 7 and docker, please ?

**Comment by loranger** [comment]
> You can change PHP version from docker image for now.

I dot not want to change PHP Version. The one you provide suits me perfectly.
But it does not work, because of composer: The issue comes from [those lines](https://github.com/openclassify/openclassify/blob/master/docker-compose.yml#L26-L28)

**Comment by MostafaMoradii** [comment]
docker-compose issue was fixed

**Comment by loranger** [comment]
Thank you !
