### ISSUE TITLE
"Show phone number" doesn't works

### ISSUE THREAD

**Issue by fatihalp** [openclassify/openclassify#133]
![image](https://user-images.githubusercontent.com/219454/68277814-0ef5ea80-0081-11ea-8b36-a1987f76c518.png)

**Comment by Diatrex** [comment]
vedat fixed the error, there was a file missing, you can check vedat's pull request

**Comment by fatihalp** [comment]
not fixed yet?

just fresh installed. https://demo.openclassify.com/advs/adv/8/apple-macbook-pro-15inc-2013


![image](https://user-images.githubusercontent.com/219454/68490948-f6d9c300-025a-11ea-9825-2245642a6ed1.png)

**Comment by fatihalp** [comment]
check while no plugin is installed
