### ISSUE TITLE
Site is opening in English even if only Arabic selected

### ISSUE THREAD

**Issue by fatihalp** [openclassify/openclassify#156]
![image](https://user-images.githubusercontent.com/219454/69353490-a10c0e80-0c8f-11ea-86c1-a5944d656cd4.png)

https://sooqalmaftuh.com

**Comment by fatihalp** [comment]
Check in pyrocms 3.7 is still have this error. If still have error report to pyrocms project.

**Comment by Diatrex** [comment]
Site is opening in English even if only Arabic is selected even after updating to the new version of pyrocms 3.7
The translation worked for the default theme of pyrocms 3.7, but when updating openclassify to 3.7, the bug still occurs
