### ISSUE TITLE
Locations will be optional (Like Country, City, District, Village)

### ISSUE THREAD

**Issue by fatihalp** [openclassify/openclassify#169]
When you disabled it in settings it wont show in post ad and ad search

**Comment by Diatrex** [comment]
can you explain please @fatihalp

**Comment by fatihalp** [comment]
we wont show country to user (front end) if disabled from setting

**Comment by Diatrex** [comment]
there is 4 settings in location module setting:
- Home Page Location Field: there is no location field in the base theme home page.
- List Page Location Field: it is already working when you disable it from the settings.
- Detail Page Location Field: it is already working when you disable it from the settings.
- Show Search Location Button: there is no location button in the base theme.
@fatihalp
