### ISSUE TITLE
Min size of images information

### ISSUE THREAD

**Issue by fatihalp** [openclassify/openclassify#314]
![image](https://user-images.githubusercontent.com/219454/74408495-a4093c00-4e45-11ea-92f8-36ba387813b2.png)

**Comment by ozcan-durak** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.
