### ISSUE TITLE
User Registration activation_mode is always automatic

### ISSUE THREAD

**Issue by geri777** [openclassify/openclassify#547]
Not sure if this is a setup problem on my side or a regression in the application.
However, when I register a new user, the Register2FormHandler.php of the addon "visiosoft\profile-module" is called. 
In contrast to the RegisterFormHandler.php of the core module "anomaly\user-module" it has no switch for the activation_mode. It always activates the user immediately.
Can I deactivate the visiosoft addon for user registration?

**Comment by fatihalp** [comment]
There is options in settings -> modules -> users related that @geri777

**Comment by geri777** [comment]
I know, I have set the activation mode to "send an email to users".

**Comment by geri777** [comment]
Have you been able to reproduce the issue?

**Comment by fatihalp** [comment]
Hi @geri777  we don't use that activation method right now. you'can just change user activation in profile module. 

We'll fix and update this.

**Comment by fatihalp** [comment]
We fixed @geri777
