### ISSUE TITLE
Openclassify app.js error

### ISSUE THREAD

**Issue by abhalera** [openclassify/openclassify#616]
Hi all,

I am a member of residents welfare association of an apartment complex in Bangalore, India and am an Electronics Engineer by profession.
I was looking for something like openclassify which I wanted to enable for our residents so that they can post free ads within the community. I tried installing openclassify on my local wampp server using the documentation. Everything works fine but I get the 404 app.js not found error when I land on the site.  I tried to look for online help but I didn't find any openclassify discussion forums where I can find the solution for this problem. 
As I possess only a very basic knowledge of web technologies, I am unable to fix it myself and hence thought of writing to the developers. Please help me in getting this fixed if you can. Your help will be really appreciated by our community.

Thanks and Best Regards,
    Amit V. Bhalerao
![openclassify_error](https://user-images.githubusercontent.com/4078613/87854138-42d22100-c92d-11ea-9adf-f3a8e97bbf5c.PNG)

**Comment by abhalera** [comment]
![openclassify_error_2](https://user-images.githubusercontent.com/4078613/87906622-9d2fc680-ca80-11ea-843b-77a8bae813d5.PNG)

**Comment by abhalera** [comment]
Is anybody there?

**Comment by fatihalp** [comment]
Hello @abhalera 

We're using app.js if theme is using vuejs or npm realated package. It's not realated with it. I believe you've no cats?

**Comment by abhalera** [comment]
Thanks a lot for the response. "I believer you've not cats?", I did not understand that part. I am a VLSI engineer and I am trying to set this up for my apartment. I'm not. a web developer to understand the lingo.  Could you please have a zoom call with me to set it up on my local server? I would really be grateful. You have a great product and our community needs it. All our residents would really be appreciating this if this can be done on a local server. I know you guys are busy and the primary focus is to make money, but as you have made this project and open source, any help from you to make it useful to communities would really be appreciated. I personally have already forwarded this to all my communities so that they can get benefited from this great tool that you have developed. Thanks 👍

**Comment by fatihalp** [comment]
@abhalera I mean that it's not related with app.js file. Maybe you didn't create any cats? 

We can't give support for your machine but if you want would give promotion code on cloud up to %50 discount. If you're not developer it'll be one click all setup, update and backup etc. It's using AWS.


Just mail to info@openclassify.com if you interested.
