### ISSUE TITLE
Profile ad not show listen

### ISSUE THREAD

**Issue by lokmana** [openclassify/openclassify#699]
Version openclassify-1.30.6 directory public_html/addons/default/visiosoft/profile-module/resources/assets/js file ads.js bug this line has an error dropdown += getBlock('profile/dropdown-ad', {'id': id}) + "</div></div>"; #699

**Comment by lokmana** [comment]
Version openclassify-1.30.6 directory public_html/addons/default/visiosoft/profile-module/resources/assets/js file ads.js bug this line has an error dropdown += getBlock('profile/dropdown-ad', {'id': id}) + "</div></div>"; #699

**Comment by fatihalp** [comment]
This is fixed with new version. Is it ok @lokmana ?
