### ISSUE TITLE
Error after php artisan install --ready (or web based install)

### ISSUE THREAD

**Issue by hemidzada** [openclassify/openclassify#891]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function getNamespace() on null
$name = str_replace('theme::', $this->theme->getNamespace() . '::', $name);

sabir@LAPTOP-BVV34BIF MINGW64 /c/wamp64/www/oc
$ php artisan install --ready
1/61 Running core migrations.

I've tried several ways on the server, localde. However, he finally gets the same error. I used PHP versions 7.2, 7.3, 7.4. Finally, I did exactly the same with the youtube video. But the result is the same.

**Comment by ozcan-durak** [comment]
Have you tried to run over Php 7.2.19

**Comment by hemidzada** [comment]
> Have you tried to run over Php 7.2.19

Yes, I tried 7.2.19, it gave phpmyadmin error. So I tried 7.2.18 as in the video. I keep getting the same error.

**Comment by hemidzada** [comment]
> Have you tried to run over Php 7.2.19

Which version of composer do I need to install with?
When I load 2 provinces I get the following errors, so I am loading with 1.

  Problem 1
    - anomaly/streams-composer-plugin is locked to version v1.1.5 and an update of this package was not requested.
    - anomaly/streams-composer-plugin v1.1.5 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by hemidzada** [comment]
> Have you tried to run over Php 7.2.19

It somehow loaded after many attempts.
(I don't know how)
However, there are still the same errors. You can check it at https://www.list.az/.
note: i installed with CLI
