### ISSUE TITLE
Openclassify on AWS install

### ISSUE THREAD

**Issue by ale4** [openclassify/openclassify#924]
I was trying to understand how to install OpenClassify on AWS, so dev sent me here.
I looked at videos, but can't get it.
Anyone?

**Comment by fatihalp** [comment]
Have you processed this doc?

https://github.com/openclassify/openclassify#installation

**Comment by ale4** [comment]
It is not clear for me.
The description given is probably for someone who is familiar w Laravel. An email once I got  from someone yours states that "this is a standard Laravel install process". I do not know what the "standards install process" within Laravel.
Unfortunately, I am not familiar w it and do not understand most of the instructions. Perhaps (most probably) my knowledge is obsolete (while ago did anything last time, and never did it on AWS), or there is Laravel particular installation "know-how" involved, not sure. 
Nevertheless, is there any way to have more details/insights on each step?

**Comment by fatihalp** [comment]
@ale4 openclassify is based on laravel which is most popular backend framework. Installation is same with laravel. Perhaps it's better to use it on cloud
